
spring:
  redis:
    host: 118.24.22.139
    port: 8742
    password:
    database: 0
    lettuce:
      pool:
        max-active: 32
        max-wait: 300ms
        max-idle: 16
        min-idle: 8
server:
  port: 8082