
spring:
  redis:
    host: 10.204.125.208
    port: 6380
    password: redis-isky
    database: 0
    lettuce:
      pool:
        max-active: 32
        max-wait: 300ms
        max-idle: 16
        min-idle: 8
server:
  port: 8082