server:
  port: 8080


spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://118.24.22.139:3306/myTest?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
    platform: user
    schema-username: root
    schema-password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      auto-commit: true
      max-lifetime: 1800000
      pool-name: DatebookHikariCP
      minimum-idle: 5
      connection-test-query: SELECT 1
      idle-timeout: 30000
      maximum-pool-size: 15
#    schema: classpath:schema-department.sql,classpath:schema-department2.sql
  wjs:
    person-name: 温建水
  resources:
    static-locations:

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.wjs.mybatis.pojo
  configuration:
    call-setters-on-nulls: true
#  config-location:classpath:mybatis-config.xml


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#showSql
logging:
  level:
    com:
      example:
        mapper : debug